name: Pydroid3 App Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any pip packages your Pydroid3 app needs
          # pip install requests

      - name: Run Python script
        run: |
          echo "Running demo script"
          # Replace with your Python file if needed
          python main.py
